hl7au/au-fhir-core

input/pagecontent/downloads.md

Related to https://github.com/hl7au/au-fhir-core/issues/87. 
Updated downloads page to include additional information about the IG downloadable. 
Added a section and csv/excel downloadable files, this is now consistent with US Core. 
Some context around this
No changes in line of "use in an unintended fashion e.g. using internal files inside the downloaded site" as the csv/excel are provided for people that want to work with those specific formats. The tooling functionality to produce these is maintained by Grahame and the tooling team (many chats in chat.fhir.org about this). 
Terminology bindings are shown as 'canonical URL | FHIR version', which is consistent with the presentation in Terminology Bindings view in the IG.

Update Downloads page 

---

input/examples/immunization-zoster-notgiven.xml
input/intro-notes/StructureDefinition-au-core-immunization-intro.md
input/resources/au-core-immunization.xml

Fixes https://jira.hl7.org/browse/FHIR-44658
Fixes https://jira.hl7.org/browse/FHIR-44657
* Remove must support from Immunization.identifier
* Remove must support from Immunization.statusReason
* Remove request for feedback notes related to the two JIRAs
* Removed Immunization.statusReason from examples

Remove must support for Immunization.identifier & statusReason

---

input/intro-notes/StructureDefinition-au-core-practitionerrole-notes.md
input/resources/au-core-client.xml
input/resources/au-core-server.xml

Fixes https://github.com/hl7au/au-fhir-core/issues/127. 
Changes made: 
1. In PractitionerRole Notes
- removed HPI-I from _identifier_ search parameter (it only requires searching by Medicare Provider Number as a SHOULD now)
- removed example for as searching Practitioner Role by an IHI
2. Updated AU Core Client CapabilityStatement
3. Updated AU Core Server CapabilityStatement

Apply the rest of the changes for removal of support of HPI-I from PractitionerRole

---

input/intro-notes/StructureDefinition-au-core-organization-notes.md
input/intro-notes/StructureDefinition-au-core-patient-notes.md
input/pagecontent/changes.md
input/resources/au-core-client.xml
input/resources/au-core-server.xml

This PR addresses issues from the AU Core R1 Ballot for Comment aucore-blockvote-6: https://confluence.hl7.org/display/HAFWG/aucore-blockvote-6
- Corrected the search parameter for gender identity to be `gender-identity` not `patient-gender-identity` [FHIR-45057](https://jira.hl7.org/browse/FHIR-45057)
- Changed the following Organization search parameters:
- address search parameter to be SHOULD instead of SHALL [FHIR-45133](https://jira.hl7.org/browse/FHIR-45133)
- name search parameter to be SHOULD instead of SHALL [FHIR-45133](https://jira.hl7.org/browse/FHIR-45133)
- Updated change log

Changes for aucore-blockvote-6 - search parameters

---

input/examples/immunization-covid-1.xml
input/pagecontent/changes.md
input/pagecontent/general-requirements.md
input/pagecontent/terminology.md
input/resources/au-core-immunization.xml

This PR addresses issues from the AU Core R1 Ballot for Comment aucore-blockvote-15:
https://confluence.hl7.org/display/HAFWG/aucore-blockvote-15 AND https://jira.hl7.org/browse/FHIR-45968.
- Made the following changes to the AU Core Immunization:
- removed Must Support from Immunization.protocolApplied, Immunization.protocolApplied.series, Immunization.protocolApplied.targetDisease, Immunization.protocolApplied.doseNumber[x] [FHIR-44674](https://jira.hl7.org/browse/FHIR-44674), [FHIR-44656](https://jira.hl7.org/browse/FHIR-44656), [FHIR-44654](https://jira.hl7.org/browse/FHIR-44654)
- removed Must Support from Immunization.reasonCode [FHIR-44654](https://jira.hl7.org/browse/FHIR-44654), [FHIR-45968](https://jira.hl7.org/browse/FHIR-45968)
- Updated 1 example to remove elements that are …

Changes for aucore-blockvote-15: AU Core Immunization

---

input/pagecontent/changes.md
input/resources/au-core-bodyheight.xml
input/resources/au-core-bodytemp.xml
input/resources/au-core-bodyweight.xml

This PR partly addresses https://jira.hl7.org/browse/FHIR-44787, voted in https://confluence.hl7.org/display/HAFWG/aucore-blockvote-16. 
PR includes changes for the following profiles: 
- AU Core Body Height
- AU Core Body Weight
- AU Core Body Temperature
JIRA https://jira.hl7.org/browse/FHIR-46031 has been raised to reach an agreement on a suitable binding for the AU Core Waist Circumference profile with the TDG.

AU Core Vitals & Measurements: Remove Required Bindings to Metric Units (FHIR-44787)

---

input/pagecontent/changes.md
input/resources/au-core-immunization.xml

This PR addresses https://jira.hl7.org/browse/FHIR-44659.
Changes:
- updated AU Core Immunization
- updated change log (including merging two AU Core Immunization entries)

AU Core Immunization: add MS to primarySource (FHIR-44659)

---

input/examples/smokingstatus-current-smoker.xml
input/intro-notes/StructureDefinition-au-core-allergyintolerance-intro.md
input/pagecontent/changes.md
input/resources/au-core-smokingstatus.xml

Ballot - Accept the need to clarify the existing profile-specific implementation guidance to clarify representation of an allergy or intolerance statement that covers use of confirmed or unconfirmed and addresses negated

AllergyIntolerance guidance clarification

---

input/ig.xml
input/ignoreWarnings.txt
input/includes/link-list.md
input/pagecontent/changes.md
input/resources/au-core-requester.xml
input/resources/au-core-responder.xml

This PR addresses the following technical corrections: 
- https://jira.hl7.org/browse/FHIR-46035
- included dependency to current versions of IPA & Smart App Launch. The version will need to be fixed to a specific version in a publication. Noting there is a qa warning about multiple different potential matches for Smart App Launch (2.2.0 & 2.0.0) due to the IG declaring dependency on the latest and the dependency on the 2.0.0 coming through the IPA.  
- https://jira.hl7.org/browse/FHIR-45390
- and other changes
- removed dependency on the extension pack 5.1.0-snapshot
- annotated errors confirmed to be caused by tooling
- fix for https://jira.hl7.org/browse/FHIR-46032

QA fixes - including FHIR-46035 & FHIR-45390

---

input/ig.xml
input/resources/au-core-actor-requester.xml
input/resources/au-core-actor-responder.xml
input/resources/au-core-allergyintolerance.xml
input/resources/au-core-bloodpressure.xml
input/resources/au-core-bodyheight.xml
input/resources/au-core-bodytemp.xml
input/resources/au-core-bodyweight.xml
input/resources/au-core-condition.xml
input/resources/au-core-diagnosticresult-path.xml
input/resources/au-core-diagnosticresult.xml
input/resources/au-core-encounter.xml
input/resources/au-core-heartrate.xml
input/resources/au-core-immunization.xml
input/resources/au-core-location.xml
input/resources/au-core-medication.xml
input/resources/au-core-medicationrequest.xml
input/resources/au-core-organization.xml
input/resources/au-core-patient.xml
input/resources/au-core-practitioner.xml
input/resources/au-core-practitionerrole.xml
input/resources/au-core-procedure.xml
input/resources/au-core-requester.xml
input/resources/au-core-responder.xml
input/resources/au-core-resprate.xml
input/resources/au-core-rsg-sexassignedab.xml
input/resources/au-core-smokingstatus.xml
input/resources/au-core-waistcircum.xml
input/resources/searchparameter-au-core-clinical-patient.xml
input/resources/searchparameter-au-core-practitionerrole-practitioner.xml

Fixes for [FHIR-46108](https://jira.hl7.org/browse/FHIR-46108), [FHIR-46160](https://jira.hl7.org/browse/FHIR-46160) & [FHIR-46159](https://jira.hl7.org/browse/FHIR-46159): 
* Marked AU Core artefacts with the exclusion of AU Core Sex Assigned at Birth as FMM=1 & status=active
* Marked ig as FMM=1 & status=active (picking up underlying artefact status)
* Added FMM extension to AU Core Sex Assigned at Birth as FMMM=0

Fixes for FHIR-46108, FHIR-46160 & FHIR-46159: FMM=1 & status=active

---

input/intro-notes/StructureDefinition-au-core-condition-notes.md
input/intro-notes/StructureDefinition-au-core-immunization-notes.md
input/intro-notes/StructureDefinition-au-core-medicationrequest-notes.md
input/pagecontent/changes.md
input/resources/au-core-requester.xml
input/resources/au-core-responder.xml

Fixes for:
[FHIR-46167](https://jira.hl7.org/browse/FHIR-46167) MedicationRequest resource combined search parameter 'patient + intent + authoredon' should be SHOULD
[FHIR-46212](https://jira.hl7.org/browse/FHIR-46212) AU Core MedicationRequest Notes: fix combined search parameter 'patient+intent' documentation
[FHIR-46184](https://jira.hl7.org/browse/FHIR-46184) Condition search by patient+onset-date formatting issues
[FHIR-46211](https://jira.hl7.org/browse/FHIR-46211) AU Core Immunization Optional Search Parameters: combined search parameter 'patient+vaccine-code' is incorrectly listed as SHOULD
[FHIR-46209](https://jira.hl7.org/browse/FHIR-46209) Update CapabilityStatements to require MAY provide both the system and code values for location identifier, instead of SHOULD

Fix technical corrections: FHIR-46211, FHIR-46184, FHIR-46211, FHIR-46209, FHIR-46167

---

input/pagecontent/changes.md
input/resources/au-core-allergyintolerance.xml

This PR includes changes for [FHIR-44713](https://jira.hl7.org/browse/FHIR-44713): 
- Changed the AllergyIntolerance.Code binding [Indicator of Hypersensitivity or Intolerance to Substance](http://example.com/) to be extensible
- Added a new value set Adverse Reaction Substances and Negated Findings as an Additional Binding with a purpose as candidate
- Updated Change log

 AllergyIntolerance.Code refined subset bindings (https://jira.hl7.org/browse/FHIR-44713)

---

input/pagecontent/relationship.md

Link changed from AUCDI Confluence reference to AUCDI R1 publication on Sparked website.
Review completed as part of 'AUCDI page - references to R1 need updating' https://github.com/orgs/hl7au/projects/3/views/1?pane=issue&itemId=68763921

Update link to published AUCDI R1.

---

input/intro-notes/StructureDefinition-au-core-medicationrequest-notes.md
input/intro-notes/StructureDefinition-au-core-organization-notes.md
input/intro-notes/StructureDefinition-au-core-patient-notes.md
input/intro-notes/StructureDefinition-au-core-practitioner-notes.md
input/intro-notes/StructureDefinition-au-core-practitionerrole-notes.md

Change all instances of "how to search by logical id" in Notes to "how to search by id of the resource" and hyperlink to https://hl7.org/fhir/r4/search.html#id

fix for FHIR-46147

---

input/resources/au-core-rsg-sexassignedab.xml

Fix for [FHIR-46161](https://jira.hl7.org/browse/FHIR-46161).
Marked AU Core Sex Assigned at Birth as FMM=1 & status=active

Marked AU Core Sex Assigned at Birth as FMM=1 & status=active (FHIR-6161)

---

input/intro-notes/StructureDefinition-au-core-encounter-intro.md
input/resources/au-core-encounter.xml

This PR addresses issues identified during the ADHA QA review.
Changes: 
- added obligations to Encounter.reasonReference
- removed implementation guidance that refers to a non-existing element Encounter.code

AU Core Encounter :: add obligations to Encounter.reasonReference and remove obsolete guidance

---

input/resources/au-core-medicationrequest.xml
input/resources/au-core-procedure.xml

Changes to add missing obligations to:
- MedicationRequest.reasonReference in AU Core MedicationRequest
- Procedure.reasonReference in AU Core Procedure

AU Core MedicationRequest and AU Core Procedure - add obligations to .reasonReference

---

input/pagecontent/aucdi.md

Add mappings for new AUCDI R1 elements, as decided in [2024-06-27 AU Core TDG Agenda/Minutes](https://confluence.hl7.org/pages/viewpage.action?pageId=248710195):
- Medication Statement Use Date of Assertion
- Measurement and Vitals Date/Time of Measurement & Date/Time of Observation

Add mappings for new AUCDI R1 elements

---

input/intro-notes/StructureDefinition-au-core-allergyintolerance-intro.md
input/pagecontent/changes.md

Fixes https://jira.hl7.org/browse/FHIR-45039:
* Removed the first point of profile-specific implementation guidance for AU Core AllergyInterolance
* updated change log

FHIR-45039: removed guidance as per FHIR-45039

---

input/pagecontent/aucdi.md

Add mappings for new AUCDI R1 elements, as decided in [[2024-07-11 AU Core TDG Agenda/Minutes](https://confluence.hl7.org/pages/viewpage.action?pageId=256508533)](https://confluence.hl7.org/pages/viewpage.action?pageId=256508533):
* Date/Time of Measurement: Biomarkers as Observation.effectiveDateTime

Add mappings for new AUCDI R1 elements: Biomarkers

---

input/ig.xml
input/pagecontent/conformance.md
input/pagecontent/guidance.md
input/pagecontent/index.md
input/pagecontent/support.md

- Add missing conformance sub page (declaring conformance)
- Add missing guidance sub pages (med info, variance statement)
- Add security and privacy point
- Add 'support' header page in line with other headers
- Remove duplicated comparison with other IGs point.

Updated 'how to read this guide' in line with latest changes

---

input/pagecontent/variance.md

Updates to variance statement to 
- add AU Sex Assigned at Birth profile as agreed in [2024-07-03 FHIRWG Meeting Minutes](https://confluence.hl7.org/display/HAFWG/2024-07-03+FHIRWG+Meeting+Minutes)
- remove Observations profiles as the Observation resource is profiled in AU Base (only where a resource is not profiled in AU Base should those additional profiles be added)

Variance statement 

---

input/ig.xml
input/pagecontent/changes.md
input/resources/au-core-requester.xml
input/resources/au-core-responder.xml

Fix for https://jira.hl7.org/browse/FHIR-46398, changed smart app launch dependency to 2.1.0

Fix for FHIR-46398: changed smart app launch dependency to 2.1.0

---

input/pagecontent/license.md

Changes:
- Replace "license" (verb) with "licence" (noun) where appropriate
- Change "HL7 Australia Content" to "HL7 Australia content"
- Update HL7 Australia licensed under CC statement

License and Legal: QA fixes

---

input/resources/au-core-requester.xml
input/resources/au-core-responder.xml

This PR includes the following:
- updates the narrative html to include the missing multipleAnd & multipleOr requirements that are visible on the Profile Notes pages but not in the narrative of capability statements
- updates CapabilityStatement.rest.security.description to match what is in the narrative
- updates the documentation element for search parameters in the CapabilityStatements to include multipleAnd & multipleOr requirements

Fixes to add in missing CapabilityStatement documentation

---

input/pagecontent/terminology.md

Fixed QA Report issue related to broken links in the terminology page.
Noting that there are issues and warnings related to the output generated by the tooling, these were raised in Zulip for confirmation:
- https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Invalid.20XHTML.20element.20name.20in.20generated.20output
- https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Build.20Failure.20publisher.20version.201.2E6.2E15

Fix QA Report issues related to broken links

---

input/resources/au-core-requester.xml
input/resources/au-core-responder.xml

1. Encounter.status - incorrect search parameter DocumentReference-status replaced with Encounter-status
2. Immunization.vaccineCode; incorrect search parameter Immunization-status replaced with Immunization-vaccine-code
3. AU Core Requester CapabilityStatement description, missing word "that" after "AU Core Requester actor" - added.

Capability statement fixes

---

input/pagecontent/changes.md
input/resources/au-core-diagnosticresult-path.xml
input/resources/au-core-diagnosticresult.xml
input/resources/au-core-medicationrequest.xml
input/resources/au-core-patient.xml
input/resources/au-core-practitionerrole.xml
input/resources/au-core-smokingstatus.xml

This PR provides fixes for: 
- [FHIR-46419](https://jira.hl7.org/browse/FHIR-46419) PractitionerRole with data-absent-reason extension for practitioner has unexpected validation error
- [FHIR-46417](https://jira.hl7.org/browse/FHIR-46417) AU Core MedicationRequest missing data extension on authoredOn causes unexpected validation error
- [FHIR-46407](https://jira.hl7.org/browse/FHIR-46407) data-absent-reason extension on Observation effectiveDateTime element cause constraint rule validation errors
- [FHIR-46406](https://jira.hl7.org/browse/FHIR-46406) data-absent-reason extension on Patient identifier and name elements cause constraint rule validation errors
Changes to update AU Core invariants to allow data absent reason:
- AU Core Patient: au-core-pat-01, au-core-pat-02, au-core-pat-04
- …

AU Core invariants: allow data absent reason (FHIR-46419, FHIR-46417, FHIR-46407, FHIR-46406)

---

input/pagecontent/changes.md
input/resources/au-core-diagnosticresult-path.xml
input/resources/au-core-diagnosticresult.xml
input/resources/au-core-procedure.xml

[FHIR-46728](https://jira.hl7.org/browse/FHIR-46728)
Remove incorrect Obligations from:
* AU Core Pathology Result Observation - Observation.hasMember.reference & Observation.specimen.reference
* AU Core Diagnostic Result Observation -  Observation.hasMember.reference
* AU Core Procedure - Procedure.bodySite
Change log entries.

Remove incorrect Obligations (FHIR-46728)

---

input/pagecontent/changes.md
input/resources/au-core-requester.xml
input/resources/au-core-responder.xml

This PR fixes [FHIR-46546](https://jira.hl7.org/browse/FHIR-46546)
Changes:
* AU Core Requester CapabilityStatement: add entry for DocumentReference and RelatedPerson
* AU Core Responder CapabilityStatement: add entry for DocumentReference and RelatedPerson
* Change log

Add missing resource support to AU Core Capability Statements (FHIR-46546)

---

input/examples/pathresult-covid-1.xml
input/pagecontent/changes.md
input/resources/au-core-diagnosticresult-path.xml
input/resources/au-core-diagnosticresult.xml

This PR fixes the following.
AU Core Diagnostic Result Observation
* [FHIR-48331](https://jira.hl7.org/browse/FHIR-48331) hasMember.reference to min cardinality of 0
* [FHIR-46737](https://jira.hl7.org/browse/FHIR-46737) Remove MustSupport and Obligation from identifier, interpretation, note, method and referenceRange elements
AU Core Pathology Result Observation
* [FHIR-46731](https://jira.hl7.org/browse/FHIR-46731) hasMember.reference and specimen.reference to min cardinality of 0
* [FHIR-46732](https://jira.hl7.org/browse/FHIR-46732) Remove MustSupport and Obligation from identifier, method and note elements
Changes to:
* Change log
* AU Core Pathology Result Observation
* AU Core Diagnostic Result Observation

Remove MS, Obligations and cardinality from DiagResult & PathResult (FHIR-48331, FHIR-46737, FHIR-46731, FHIR-46732)

---

input/pagecontent/comparison.md

Remove duplicate entry of 'Device - performer, observer', replace with 'Device Use Statement (IPS).
https://github.com/orgs/hl7au/projects/8/views/1?pane=issue&itemId=79393106

Fix duplicate entry on IPS Additional Profiles

---

input/pagecontent/index.md

Fix for https://jira.hl7.org/browse/FHIR-47180.

Corrected AU TDG name in the Home page (FHIR-47180)

---

input/pagecontent/general-guidance.md

Fix for [FHIR-47019](https://jira.hl7.org/browse/FHIR-47019) & [FHIR-46724](https://jira.hl7.org/browse/FHIR-46724):
* Change "Otherwise, when responding to a query, it is recommended that servers avoid using inline contained resources to represent the returned data." to "Otherwise, it is recommended that an AU Core Responder avoids the use of contained resources unless the referenced resource does not have an independent existence apart from the resource that contains it and cannot be identified independently.”
Fix for [FHIR-46739](https://jira.hl7.org/browse/FHIR-46739) (encompasses changes for [FHIR-47018](https://jira.hl7.org/browse/FHIR-47018) & [FHIR-47021](https://jira.hl7.org/browse/FHIR-47021)):
* Replace "code.coding contains the primary concept (no body site information)" with …

Gen Guidance - Contained Resources & Representing body site changes

---

input/intro-notes/StructureDefinition-au-core-procedure-intro.md
input/pagecontent/comparison.md
input/pagecontent/profiles-and-extensions.md
input/pagecontent/terminology.md

Fix for [FHIR-47022](https://jira.hl7.org/browse/FHIR-47022)
* Change text to reference FHIR Extensions Pack instead of base FHIR spec
* Fix typo "The following extension are..." to extensions
Fix for [FHIR-46882](https://jira.hl7.org/browse/FHIR-46882)
* Delete Concept Map section from Terminology page
Fix for [FHIR-46874](https://jira.hl7.org/browse/FHIR-46874)
* Change text from "US Core does not include requirements for Suppressed Data." to "AU Core compliant resources are compliant with US Core requirements for Suppressed Data."
Fix for [FHIR-46738](https://jira.hl7.org/browse/FHIR-46738)
* Delete "In an exchange with the My Health Record system Procedure.status is "completed"
* Change 'should' to 'is recommended to use' in "A procedure including an implantable device should..."

Text changes to Profiles and Extensions, Terminology, Comparison and Procedure intro

---

input/pagecontent/changes.md
input/pagecontent/general-guidance.md
input/pagecontent/medicine-information.md

Fix for [FHIR-47194](https://jira.hl7.org/browse/FHIR-47194) & [FHIR-46740](https://jira.hl7.org/browse/FHIR-46740) - Read/Search Syntax guidance page:
* Add text regarding examples not demonstrating url encoding for special characters
* Replace "All the search interactions in this guide use the GET command with the following syntax:" with ""All the search interaction examples in this guide use the HTTP GET method with the following syntax:"
Fix for [FHIR-46741](https://jira.hl7.org/browse/FHIR-46741) & [FHIR-46742](https://jira.hl7.org/browse/FHIR-46742) - Medicinal Product Identification guidance:
* Change text describing medicinal product identification of extemp and non-extemp medications

Read/Search Syntax & Medicinal Product Identification guidance changes

---

input/intro-notes/StructureDefinition-au-core-location-notes.md
input/pagecontent/changes.md
input/resources/au-core-requester.xml
input/resources/au-core-responder.xml

Fix for [FHIR-47107](https://jira.hl7.org/browse/FHIR-47107)
* Changed Location address search parameter from SHALL to SHOULD in requester and responder CapStats and Location resource notes (table and example)

Change Location address search parameter from SHALL to SHOULD (FHIR-47107)

---

input/intro-notes/StructureDefinition-au-core-medicationrequest-notes.md
input/pagecontent/changes.md
input/resources/au-core-requester.xml
input/resources/au-core-responder.xml

Fix for [FHIR-47073](https://jira.hl7.org/browse/FHIR-47073)
* Change patient+intent & patient+intent+status to SHOULD, add patient+status as SHALL in requester and responder CapStats and MedRequest resource notes (table and examples)

MedRequest search parameters: change patient+intent & patient+intent+status to SHOULD, add patient+status as SHALL (FHIR-47073)

---

input/intro-notes/StructureDefinition-au-core-organization-notes.md
input/pagecontent/changes.md
input/resources/au-core-requester.xml
input/resources/au-core-responder.xml

Fix for [FHIR-47109](https://jira.hl7.org/browse/FHIR-47109)
* Change Organization name search param from SHOULD to SHALL in requester and responder CapStats, Organization notes (table and example)

Change Organization name search parameter from SHOULD to SHALL (FHIR-47109)

---

input/ig.xml
input/includes/menu.xml
input/pagecontent/fhirartefacts.md
input/pagecontent/general-requirements.md
input/pagecontent/index.md

Fix for [FHIR-47184](https://jira.hl7.org/browse/FHIR-47184)
* Change Support page to be parent of Downloads and License and Legal pages 
* Add Artefacts Summary to FHIR Artefacts drop down menu
Fix for [FHIR-46951](https://jira.hl7.org/browse/FHIR-46951)
* Remove "The core specification provides guidance for what to do in this situation" from Missing Must Support and Mandatory Data.
Additional changes out of scope of the above ballot tickets:
Changes made in AU Base on the Menu, Table of Contents and FHIR Artefacts navigation page to align with AU Base as per https://jira.hl7.org/browse/FHIR-47167
* Corrections to parent/child pages in Table of Contents
* Update Index page with FHIR Artefacts grouping page and Artefacts Summary as child page
* Add Artefact Summary to drop down menu

Menu changes, Missing MS guidance change (FHIR-47184, FHIR-46951)

---

input/resources/au-core-diagnosticresult-path.xml
input/resources/au-core-diagnosticresult.xml

Refactor au-core-obs-01 expression in AU Core Pathology Result Observation and AU Core Diagnostic Result Observation, resolving current [QA error]( https://build.fhir.org/ig/hl7au/au-fhir-core/qa.html#_scratch_repo_input_examples_observation-masked):
Observation​.effective​.ofType(Period) (l23​/c20) | error | Constraint failed: au-core-obs-01: 'Date shall be at least to day or, if not available, the Data Absent Reason extension shall be present' (defined in http://hl7.org.au/fhir/core/StructureDefinition/au-core-diagnosticresult)
FYI, see also 
:test_tube: [Test with FHIRPath-Lab](https://fhirpath-lab.com/FhirPath?parameters=N4IgpgHgDgTmDO8CWB7AdiAXCAFDgJAC4AWS8ABGeQCYCGhYAKkgLZiUtQA2SC5RpeADpCKAMqEYSNAHMcASiFcwskgvIA+ALzkAjAAZ55WmmrlIDNMnQ4A5MUKEomAPQviXAOxCUMGS4AzUhgXCRgAVwBjQnC4ABEwAOkk …

Refactor au-core-obs-01 expression in diagnostic and pathology result observations

---

input/includes/observation_vitalsigns_guidance.md
input/intro-notes/StructureDefinition-au-core-location-notes.md
input/intro-notes/StructureDefinition-au-core-practitionerrole-notes.md
input/intro-notes/StructureDefinition-au-core-smokingstatus-notes.md

This PR addresses [a project backlog item](https://github.com/orgs/hl7au/projects/8?pane=issue&itemId=85146774) to perform various QA updates.
Note that item #1 was not done because SNOMED has retired the existing codes without providing a simple alternative, and Sparked needs to decide how it wants to handle Allergy / Intolerance negation going forward before changes can be applied to the IG.
Note that no change was performed for item #8 because the notes section actually applies to multiple examples and as such is not specific to the page the reviewer identified.

Terminology QA

---

input/ig.xml
input/resources/au-core-requester.xml
input/resources/au-core-responder.xml

Fixes #315. 
Changes:
1. Changed IG to be fmm=2, standards status=trial-use
2. Updated IG dependencies to the current version of Smart App Launch, and changed to v2.2.0 in both CapabilityStatements

Updates to IG & dependencies (#315)

---

input/examples/allergyintolerance-lactose.xml
input/examples/encounter-covid-admin-1.xml
input/examples/patient-bennelong-anne.xml
input/examples/patient-wang-li.xml

1. Fix to replace national identifiers for local identifiers for personas that are not Services Australia
2. Fix for Anne Bennelong's address to match the preferred language
3. Remove asserter from example allergyintolerance-lactose to reduce the instances of 'asserter' in AU Core

QA fix for examples: identifier corrections, address correction

---

input/pagecontent/changes.md
input/resources/au-core-patient.xml
input/resources/searchparameter-au-core-clinical-patient.xml
input/resources/searchparameter-au-core-practitionerrole-practitioner.xml

This PR provides fixes for FHIR-46268 and FHIR-48749. 
Changes:
- [FHIR-46268](https://jira.hl7.org/browse/FHIR-46268)
- removed cardinality constraint from the identifier slice in AU Core Patient StructureDefinition
- change log
- [FHIR-48749](https://jira.hl7.org/browse/FHIR-48749)
- updated AUCoreClinicalPatient and AUCorePractitionerRolePractitioner  SearchParameter descriptions

Fixes for FHIR-46268 and FHIR-48749

---

input/intro-notes/StructureDefinition-au-core-medicationrequest-intro.md
input/intro-notes/StructureDefinition-au-core-medicationstatement-intro.md
input/resources/au-core-medicationrequest.xml
input/resources/au-core-medicationstatement.xml

Fix for [FHIR-50800](https://jira.hl7.org/browse/FHIR-50800).
Changes:
- removed obligations from MedicationRequest.medicationReference and MedicationStatement.medicationReference
- updated implementation guidance for both profiles

 AU Core MedicationStatement & AU Core MedicationRequest: Remove redundant obligations from medicationReference (FHIR-50800)

---

input/pagecontent/comparison.md

Add PractitionerRole (IPS) additional requirements to profile comparison to type  PractitionerRole.code to CodeableConceptIPS.
Changes in
- profile comparison table, green to yellow for AU Core PracitionerRole
- add entry in IPS additional requirements table

Profile comparison - add PractitionerRole (IPS) additional requirements

---

input/resources/au-core-diagnosticresult-path.xml

- remove short on Observation.effective[x] from AU Core Pathology Result Observation as it is inherited from AU Base.

QA Fix : remove short on Observation.effective[x] from AU Core Pathology Result Observation

---

input/pagecontent/comparison.md

Comparison page changes to include level 4 headings in ToC
Changes: 
- Adjusted heading levels (shifted all down one level).
- Included workaround to include h1, h2, h3, and h4 in markdown-toc, since updating the template to support h4 headings is not straightforward.

Comparison page ToC changes to include h4 headings

---

input/pagecontent/comparison.md

Fixed for [FHIR-52186](https://jira.hl7.org/browse/FHIR-52186)
IPS has made a change to the supported type - in the Medication (IPS) profile Medication.ingredient.strength is no longer typed to Ratio (IPS). Dead link has been removed.

Removing broken link in comparison page - FHIR-52186 

---

input/pagecontent/general-requirements.md

[FHIR-52525] (https://jira.hl7.org/browse/FHIR-52525)
Changed intro sentence of identifier table from: "The table below provides a list of AU Core profile elements that allow multiple identifier types." to: "The table below provides a list of AU Core profile elements with one or more supported identifier types." for clarity.
File changed: input/pagecontent/general-requirements.md

Clarify intro sentence for Choice of Identifiers table (FHIR-52525) 
