hl7au/au-fhir-core

- input/intro-notes/StructureDefinition-au-core-patient-intro.md
Hello, please review this PR with changes:
- moved Gender Identity and related concepts to above Profile specific implementation guidance
- fixed formatting issue on the Gender Identity and related concepts insertion
Thanks
> AU Core Patient intro QA fixes

- input/intro-notes/StructureDefinition-au-core-condition-intro.md
> Updated AU Core Condition to current JIRA Change Requests

- input/resources/au-core-server.xml
Related to https://github.com/hl7au/au-fhir-core/issues/121
Added missing interactions to AU Core Server. 
AU Core Client changes to follow.
> AU Core Server & Client CapabilityStatement change to add missing interactions

- input/resources/au-core-client.xml
- input/resources/au-core-server.xml
Fixes https://github.com/hl7au/au-fhir-core/issues/121. 
Add missing interactions to AU Core Client.
> AU Core Server & Client CapabilityStatement - add missing interactions (https://github.com/hl7au/au-fhir-core/issues/121)

- input/examples/patient-banks-mia-leanne.xml
- input/ig.xml
- input/intro-notes/StructureDefinition-au-core-patient-intro.md
- input/intro-notes/StructureDefinition-au-core-rsg-sexassignedab-intro.md
- input/pagecontent/aucdi.md
- input/pagecontent/examples.md
- input/pagecontent/profiles-and-extensions.md
- input/resources/au-core-rsg-sexassignedab.xml
Apply change for https://jira.hl7.org/browse/FHIR-44856 including:
* add profile of extension
* add profile intro page to provide a link to an example that demonstrates the profile
* changed Patient mia banks example
* changed aucdi mapping to add comment
* edited profiles-and-extensions.md to add an entry for the profile of the extension
* edited examples.md to add entries for the three supported extensions
* edited au core patient intro to add text for Gender Identity and Related Concepts
> Profile for Sex Assigned at Birth

- input/intro-notes/StructureDefinition-au-core-allergyintolerance-intro.md
- input/intro-notes/StructureDefinition-au-core-bloodpressure-intro.md
- input/intro-notes/StructureDefinition-au-core-bodyheight-intro.md
- input/intro-notes/StructureDefinition-au-core-bodytemp-intro.md
- input/intro-notes/StructureDefinition-au-core-bodyweight-intro.md
- input/intro-notes/StructureDefinition-au-core-condition-intro.md
- input/intro-notes/StructureDefinition-au-core-encounter-intro.md
- input/intro-notes/StructureDefinition-au-core-heartrate-intro.md
- input/intro-notes/StructureDefinition-au-core-immunization-intro.md
- input/intro-notes/StructureDefinition-au-core-medication-intro.md
- input/intro-notes/StructureDefinition-au-core-organization-intro.md
- input/intro-notes/StructureDefinition-au-core-patient-intro.md
- input/intro-notes/StructureDefinition-au-core-practitioner-intro.md
- input/intro-notes/StructureDefinition-au-core-practitionerrole-intro.md
- input/intro-notes/StructureDefinition-au-core-procedure-intro.md
- input/intro-notes/StructureDefinition-au-core-provenance-intro.md
- input/intro-notes/StructureDefinition-au-core-resprate-intro.md
- input/intro-notes/StructureDefinition-au-core-waistcircum-intro.md
- input/pagecontent/aucdi.md
- input/pagecontent/index.md
Improvements to wording and spacing across STU Notes. Removed those are no longer relevant.
> STU Notes Update

- input/pagecontent/aucdi.md
- input/pagecontent/changes.md
Fixes #147 .
Changes: 
- Updated AUCDI mappings table
- Updated Change log
> Updated mappings of AUCDI Procedure Completed Event to Procedure only  (https://github.com/hl7au/au-fhir-core/issues/147)

- input/examples/bodyheight-1.xml
- input/examples/bodytemp-1.xml
- input/examples/bodyweight-1.xml
- input/examples/immunization-covid-1.xml
- input/examples/immunization-zoster-notgiven.xml
- input/examples/pulserate-1.xml
- input/examples/smokingstatus-current-smoker.xml
- input/intro-notes/StructureDefinition-au-core-bloodpressure-intro.md
- input/intro-notes/StructureDefinition-au-core-bodyheight-intro.md
- input/intro-notes/StructureDefinition-au-core-bodytemp-intro.md
- input/intro-notes/StructureDefinition-au-core-bodyweight-intro.md
- input/intro-notes/StructureDefinition-au-core-heartrate-intro.md
- input/intro-notes/StructureDefinition-au-core-immunization-intro.md
- input/intro-notes/StructureDefinition-au-core-resprate-intro.md
- input/intro-notes/StructureDefinition-au-core-waistcircum-intro.md
- input/pagecontent/changes.md
- input/pagecontent/general-requirements.md
- input/resources/au-core-bloodpressure.xml
- input/resources/au-core-bodyheight.xml
- input/resources/au-core-bodytemp.xml
- input/resources/au-core-bodyweight.xml
- input/resources/au-core-immunization.xml
- input/resources/au-core-resprate.xml
- input/resources/au-core-smokingstatus.xml
- input/resources/au-core-waistcircum.xml
This PR addresses issues from the AU Core R1 Ballot for Comment aucore-blockvote-3: https://confluence.hl7.org/display/HAFWG/aucore-blockvote-3
This PR fixes the following issues:
- https://jira.hl7.org/browse/FHIR-44653
- https://jira.hl7.org/browse/FHIR-45223
- https://jira.hl7.org/browse/FHIR-44786
Changes:
JIRA | Changes
---- | ----
https://jira.hl7.org/browse/FHIR-44563 | Removed MS from performer, performer.function, and performer.actor in AU Core Immunizartion <br>Updated Change Log <br> Removed Request for Feedback <br <Updated examples
https://jira.hl7.org/browse/FHIR-44786| Removed MS from performer in AU Core Blood Pressure, AU Core Body Height, AU Core Body Weight, AU Core Heart Rate, AU Core Respiration Rate, and AU Core Waist Circumference profiles<br>Updated examples (not …
> Removal of Must Support from the performer element (aucore-blockvote-3)

- input/ig.xml
- input/includes/menu.xml
- input/includes/security.md
- input/pagecontent/changes.md
This PR fixes [FHIR-45067](https://jira.hl7.org/browse/FHIR-45067).
Added a security page
Updated ig.xml
Updated changes.md
> Changes for FHIR-45067: Security and Privacy

- input/examples/bun-mcc.xml
- input/examples/patient-dan-harry.xml
- input/pagecontent/aucdi.md
- input/pagecontent/general-requirements.md
- input/pagecontent/index.md
This PR addresses some but not all issues from the AU Core R1 Ballot for Comment aucore-blockvote-8: https://confluence.hl7.org/display/HAFWG/aucore-blockvote-8
Fixes for the following are in this PR:
- [FHIR-45166](https://jira.hl7.org/browse/FHIR-45166?src=confmacro)
- [FHIR-45159](https://jira.hl7.org/browse/FHIR-45159?src=confmacro)
- [FHIR-45102](https://jira.hl7.org/browse/FHIR-45102?src=confmacro)
- [FHIR-45065](https://jira.hl7.org/browse/FHIR-45065?src=confmacro)
- [FHIR-44957](https://jira.hl7.org/browse/FHIR-44957?src=confmacro)
> Changes for aucore-blockvote-8 part 3

- input/intro-notes/StructureDefinition-au-core-heartrate-intro.md
Changes for https://jira.hl7.org/browse/FHIR-44861.
> Guidance for Pulse Rate (FHIR-44861)

- input/pagecontent/changes.md
- input/pagecontent/index.md
- input/resources/au-core-client.xml
- input/resources/au-core-server.xml
This PR provides a fix for https://jira.hl7.org/browse/FHIR-45113. 
Changes: 
- updated index.md
- updated AU Core Client and AU Core Server CapabilityStatements
- updated change log
> Remove reference to Bulk Data Access implementation guide (FHIR-45113)

- input/examples/condition-noknown.xml
- input/ig.xml
- input/intro-notes/StructureDefinition-au-core-condition-intro.md
This PR addresses [FHIR-45058](https://jira.hl7.org/browse/FHIR-45058) voted in [aucore-blockvote-16](https://confluence.hl7.org/display/HAFWG/aucore-blockvote-16). 
Changes: 
- updated intro content
- updated ig.xml
- added one example
> AU Core Condition: Add guidance on no known problems (FHIR-45058)

- input/intro-notes/StructureDefinition-au-core-encounter-notes.md
- input/intro-notes/StructureDefinition-au-core-medicationrequest-notes.md
- input/pagecontent/changes.md
- input/resources/au-core-requester.xml
- input/resources/au-core-responder.xml
This PR addresses:
- https://jira.hl7.org/browse/FHIR-45991 AU Core MedicationRequest: remove search parameters identifier & category
- https://jira.hl7.org/browse/FHIR-45603 AU Core Encounter: remove search parameter discharge-disposition
- https://jira.hl7.org/browse/FHIR-45954 AU Core Encounter: remove type search parameter
Changes to:
- change log
- Notes pages for AU Core Encounter & AU Core MedicationRequest
- AU Core Requester CapabilityStatement
- AU Core Responder CapabilityStatement
> Changes for FHIR-45991, FHIR-45603, FHIR-45954  (search param removal)

- input/pagecontent/changes.md
- input/resources/au-core-organization.xml
> Fix FHIRPath expression (FHIR-46103)

- publication-request.json
Fixes #206. 
Updated the introduction in publication-request.json to align with the content from the deprecated package-list.json.
> publication-request.json introduction update (https://github.com/hl7au/au-fhir-core/issues/206)

- input/intro-notes/StructureDefinition-au-core-bodyheight-intro.md
- input/intro-notes/StructureDefinition-au-core-bodytemp-intro.md
- input/intro-notes/StructureDefinition-au-core-bodyweight-intro.md
- input/intro-notes/StructureDefinition-au-core-waistcircum-intro.md
Removed the 'Request for feedback' on [FHIR-44787](https://jira.hl7.org/browse/FHIR-44787) banner from AU Core Body Height, AU Core Body Weight, AU Core Body Temperature and AU Core Waist Circumference.
> Remove request for feedback on FHIR-44787

- input/includes/security.md
- input/intro-notes/StructureDefinition-au-core-encounter-notes.md
- input/pagecontent/changes.md
- input/resources/au-core-requester.xml
- input/resources/au-core-responder.xml
Changes for the following:
- [FHIR-46067](https://jira.hl7.org/browse/FHIR-46067) AU Core Requester & Responder CapabilityStament Security requirements are not consistent with AU Core Security and Privacy page
- [FHIR-46068](https://jira.hl7.org/browse/FHIR-46068) Strengthen AU Core Transport Layer Security (TLS) Requirements
- [FHIR-46057](https://jira.hl7.org/browse/FHIR-46057) AU Core Encounter: remove search parameter identifier
> Recent TDG changes: FHIR-46067, FHIR-46068, FHIR-46057

- input/intro-notes/StructureDefinition-au-core-patient-notes.md
- input/pagecontent/changes.md
- input/resources/au-core-requester.xml
- input/resources/au-core-responder.xml
Fixes https://jira.hl7.org/browse/FHIR-45410:
* Updated Patient Notes
* Updated CapabilityStatement in narrative, and in search param documentation
* Updated change log
> FHIR-45410: comparators & multipleAnd changes for birthdate

- input/pagecontent/changes.md
- input/resources/au-core-immunization.xml
- input/resources/au-core-medication.xml
- input/resources/au-core-medicationrequest.xml
Related to AU Base changes in https://github.com/hl7au/au-fhir-base/pull/848. Fixes https://jira.hl7.org/browse/FHIR-46391
Changed: 
- AU Core Immunization
- AU Core Medication
- AU Core MedicationRequest
> Refactoring slices in Medication & Immunization profiles to slice by value set (FHIR-46391)

- input/resources/au-core-condition.xml
Addresses [FHIR-43848](https://jira.hl7.org/browse/FHIR-43848).
> Improve invariant text (FHIR-43848)

- input/pagecontent/comparison.md
Addresses [FHIR-46633](https://jira.hl7.org/browse/FHIR-46633).
> Add comparison of elements flagged Must Support (FHIR-46633)

- input/intro-notes/StructureDefinition-au-core-patient-notes.md
- input/pagecontent/changes.md
- input/resources/au-core-requester.xml
- input/resources/au-core-responder.xml
[FHIR-46390](https://jira.hl7.org/browse/FHIR-46390)
* AU Core Requester CapabilityStatement:  _id to SHOULD; add documentation noting difference in requester and responder; reorder in narrative so sits below SHALL.
* AU Core Requester CapabilityStatement: add documentation noting difference in requester and responder.
* AU Core Patient Notes: add documentation noting difference in requester and responder for _id
> Requester Patient _id search parameter to SHOULD [FHIR-46390]

- input/examples/condition-ckd.xml
- input/examples/condition-uti.xml
- input/examples/medicationrequest-reaptan.xml
- input/pagecontent/changes.md
Fix for [FHIR-47011](https://jira.hl7.org/browse/FHIR-47011) 
* Change MedicationRequest.reasonCode from pain management to hypertension in MedicationRequest/reaptan example
Fix for [FHIR-46955](https://jira.hl7.org/browse/FHIR-46955)
* Remove severity from Condition/ckd example
* Add severity to Condition/uti example
> Change MedicationReq/reaptan, Condition/ckd and Condition/uti examples

- input/includes/observation_notes.md
- input/includes/observation_parameters.md
- input/includes/observation_social-history_notes.md
- input/includes/observation_vitalsigns_notes.md
- input/includes/observation_vitalsigns_parameters.md
- input/intro-notes/StructureDefinition-au-core-diagnosticresult-notes.md
- input/intro-notes/StructureDefinition-au-core-diagnosticresult-path-notes.md
- input/pagecontent/changes.md
- input/resources/au-core-requester.xml
- input/resources/au-core-responder.xml
Fix for [FHIR-47171](https://jira.hl7.org/browse/FHIR-47171)
Changes applied to:
- Requester and responder CapStats
- Notes of all Observation profiles (table and Mandatory Search Parameters section)
Change log entry.
> Change Observation patient search parameter from SHALL to MAY

- input/resources/au-core-bloodpressure.xml
- input/resources/au-core-bodyheight.xml
- input/resources/au-core-bodytemp.xml
- input/resources/au-core-bodyweight.xml
- input/resources/au-core-condition.xml
- input/resources/au-core-diagnosticresult-path.xml
- input/resources/au-core-diagnosticresult.xml
- input/resources/au-core-heartrate.xml
- input/resources/au-core-medicationrequest.xml
- input/resources/au-core-patient.xml
- input/resources/au-core-procedure.xml
- input/resources/au-core-resprate.xml
- input/resources/au-core-waistcircum.xml
Renumbered invariants, starting at 1 and increasing sequentially by 1
> Reorder invariant numbering

- input/examples/medicationrequest-reaptan.xml
Fix for [FHIR-48717](https://jira.hl7.org/browse/FHIR-48717)
* Amend dosage instructions to reflect '1 tablet daily'
* Remove reference to 'as needed for pain'
> Correct dosageInstruction in MedicationRequest/reaptan example

- input/resources/au-core-responder.xml
[FHIR-46059](https://jira.hl7.org/browse/FHIR-46059) removed the search-system and history-system interactions from [AU Core Responder Capability Statement](https://build.fhir.org/ig/hl7au/au-fhir-core/CapabilityStatement-au-core-responder.html). Also formatted file, which had no indents etc.
> FHIR-46059 remove search-system, history-system interactions

- input/pagecontent/changes.md
- input/resources/au-core-actor-requester.xml
- input/resources/au-core-actor-responder.xml
- input/resources/au-core-allergyintolerance.xml
- input/resources/au-core-bloodpressure.xml
- input/resources/au-core-condition.xml
- input/resources/au-core-encounter.xml
- input/resources/au-core-immunization.xml
- input/resources/au-core-location.xml
- input/resources/au-core-medication.xml
- input/resources/au-core-medicationrequest.xml
- input/resources/au-core-organization.xml
- input/resources/au-core-patient.xml
- input/resources/au-core-practitioner.xml
- input/resources/au-core-practitionerrole.xml
- input/resources/au-core-procedure.xml
- input/resources/au-core-responder.xml
- input/resources/au-core-rsg-sexassignedab.xml
- input/resources/au-core-smokingstatus.xml
This PR fixes [FHIR-48873](https://jira.hl7.org/browse/FHIR-48873) and [FHIR-48676](https://jira.hl7.org/browse/FHIR-48676).
> Change maturity level to AFMM 2 (FHIR-48676, FHIR-48873)

- input/resources/au-core-bodyheight.xml
- input/resources/au-core-bodytemp.xml
- input/resources/au-core-bodyweight.xml
- input/resources/au-core-diagnosticresult-path.xml
- input/resources/au-core-diagnosticresult.xml
- input/resources/au-core-heartrate.xml
- input/resources/au-core-resprate.xml
- input/resources/au-core-waistcircum.xml
Fix for [FHIR-48999](https://jira.hl7.org/browse/FHIR-48999).
> Change maturity level to AFMM 2 (FHIR-48999)

- input/ig.xml
- input/includes/note-healthcareservice.md
- input/intro-notes/StructureDefinition-au-core-healthcareservice-notes.md
This PR addresses the 4 proposal improvements points raised in #335 
In addition, the incorrect date for when feedback is requested by has been fixed.
Fixes #335
> AU Core HealthcareService proposal improvements

- input/pagecontent/relationship.md
This PR fixes [FHIR-46878](https://jira.hl7.org/browse/FHIR-46878).
Changes to page [Relationship to AUCDI and other IGs](https://build.fhir.org/ig/hl7au/au-fhir-core/relationship.html#relationship-to-aucdi-and-other-igs):
> Fix for FHIR-46878

- input/intro-notes/StructureDefinition-au-core-diagnosticresult-intro.md
- input/intro-notes/StructureDefinition-au-core-diagnosticresult-path-intro.md
- input/resources/au-core-diagnosticresult.xml
Fix for [FHIR-46889](https://jira.hl7.org/browse/FHIR-46889).
> Clarify the relationship between AU Core Diagnostic Result Observation and AU Core Pathology Result Observation (FHIR-46889)

- input/pagecontent/changes.md
- input/pagecontent/comparison.md
- input/resources/au-core-immunization.xml
This PR fixes
- [FHIR-47331](https://jira.hl7.org/browse/FHIR-47331) Batch ID in immunisation.lotnumber
- [FHIR-46879](https://jira.hl7.org/browse/FHIR-46879) IPS/IPA comparison explanation
Changes
- FHIR-47331
- AU Core Immunization StructureDefinition
- changes.md
-  FHIR-46879
- comparison page
> Fixes for FHIR-46879 and FHIR-47331

- input/pagecontent/changes.md
- input/pagecontent/comparison.md
- input/resources/au-core-patient.xml
Fixes [FHIR-51033](https://jira.hl7.org/browse/FHIR-51033).
Changed:
- change log
- AU Core Patient profile
- comparison page
>  FHIR-51033 : added MS & Obligations to Patient.telecom

- input/pagecontent/medicine-information.md
https://github.com/hl7au/au-fhir-core/issues/360
- change case in example to match AMT v4 display
> Fix case in example for https://github.com/hl7au/au-fhir-core/issues/360

- input/pagecontent/comparison.md
Update to compare to US Core 8.0.0.
> Comparison page - US Core comparison to 8.0.0

- input/pagecontent/changes.md
- input/pagecontent/general-guidance.md
- input/pagecontent/medicine-information.md
Fixes [FHIR-51473](https://jira.hl7.org/browse/FHIR-51473) -add pointer to AU Base SNOMED CT Australian Edition guidance:
Changes to:
- general-guidance
- medicine-information
- change log
> FHIR-51473 - add pointer to AU Base SNOMED CT Australian Edition guidance

- input/intro-notes/StructureDefinition-au-core-bloodpressure-intro.md
- input/pagecontent/changes.md
[FHIR-49951](https://jira.hl7.org/browse/FHIR-49951) - Add Guidance for more specific blood pressure observations
Changes to:
- intro notes for AU Core Blood Pressure
- change log
> FHIR-49951 - Add Guidance for more specific blood pressure observations

- input/pagecontent/comparison.md
Move additional resource types into the CapabilityStatement additional requirements tables.
> Comparison page - move additional resource types into the CapabilityStatement additional requirements tables
